### ISSUE TITLE
[Bug] Escaped backticks interrupt highlighting

### ISSUE THREAD

**Issue by codeclown** [frigus02/vscode-sql-tagged-template-literals#12]
Thanks for this extension, it's really great!

Noticed that using escaped backticks inside the template string interrupts/breaks the highlighting:

![image](https://user-images.githubusercontent.com/211543/98026717-3ad2ba00-1e14-11eb-8722-4f6f5d55cd34.png)

I would've made a PR but couldn't get a local dev environment working. It's probably enough to do something like:

```js
// from
"end": "(?<=`)",
// to
"end": "(?<=[^\\]`)",
```

**Comment by frigus02** [comment]
Thanks for reporting. Your suggestion looks correct to me. I'm going to give this a go in the evening.

**Comment by frigus02** [comment]
The solution was different than I thought. But that makes a lot of sense. It should work fine now.

I just uploaded a new version, which should be available for update in the next few minutes.

**Comment by codeclown** [comment]
Can confirm it works:

![image](https://user-images.githubusercontent.com/211543/98227807-69f64200-1f60-11eb-95ba-27d3e12185ba.png)

Thanks!

**Comment by CherryDT** [comment]
For me it doesn't seem to work.

![image](https://user-images.githubusercontent.com/6010463/170704529-04d8bced-ef86-4efa-8a46-8922656d8f39.png)

**Comment by frigus02** [comment]
Hi @CherryDT. The extension also parses the SQL and in addition to syntax highlighting. Parsing only works for PostgreSQL. Since you're using back ticks, I assume you're using MySQL. For that I recommend using the syntax highlight-only version of the extension: https://marketplace.visualstudio.com/items?itemName=frigus02.vscode-sql-tagged-template-literals-syntax-only

Alternatively, I believe the extension also has an option to turn off diagnostics. That should also get rid of the error.

**Comment by CherryDT** [comment]
But then nevertheless it should stay within the boundaries of the template string, shouldn't it? Whatever issues it has with parsing the SQL, it should never mess up the rest of the file after the end of the string.

**Comment by frigus02** [comment]
Nevertheless, it's definitely odd that the backslash is part of the error message. I'm going to track this issue here: https://github.com/frigus02/typescript-sql-tagged-template-plugin/issues/30
